[tool.poetry]
name = "test-task-paritet"
version = "0.1.0"
description = ""
authors = ["SiberianFalcon <bq.Sokol@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^5.0.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
