# Generated by Django 5.0.7 on 2024-07-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestTaskModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "picture",
                    models.ImageField(default=None, null=True, upload_to="../images"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Test_Task_Model",
        ),
    ]
