# Generated by Django 5.0.7 on 2024-07-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_testtaskmodel_delete_test_task_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testtaskmodel",
            name="picture",
            field=models.ImageField(default=None, null=True, upload_to="images"),
        ),
    ]
